const paperURL =
  'https://image.shutterstock.com/image-vector/king-tissue-character-cartoon-style-600w-765586615.jpg';
const scissorsURL =
  'https://ravinternet.org/wp-content/uploads/2018/07/%D7%9E%D7%A1%D7%A4%D7%A8%D7%99%D7%99%D7%9D-488x360.jpg';
const stoneURL =
  'https://image.shutterstock.com/image-vector/cartoon-vector-grumpy-rock-600w-173241479.jpg';

var data = [
  {
    isOption: false,
    press: false,
    row: 1,
    column: 1,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 1,
    column: 2,
    imageUrl: stoneURL,
    team: 'A',
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 1,
    column: 3,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 1,
    column: 4,
    imageUrl: paperURL,
    Kingdom: 'A',
    team: 'A',
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 1,
    column: 5,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 1,
    column: 6,
    imageUrl: stoneURL,
    team: 'A',
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 1,
    column: 7,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 2,
    column: 1,
    imageUrl: scissorsURL,
    team: 'A',
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 2,
    column: 2,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 2,
    column: 3,
    imageUrl: null,
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 2,
    column: 4,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 2,
    column: 5,
    imageUrl: null,
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 2,
    column: 6,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 2,
    column: 7,
    imageUrl: scissorsURL,
    team: 'A',
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 3,
    column: 1,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 3,
    column: 2,
    imageUrl: null,
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 3,
    column: 3,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 3,
    column: 4,
    imageUrl: scissorsURL,
    team: 'A',
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 3,
    column: 5,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 3,
    column: 6,
    imageUrl: null,
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 3,
    column: 7,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 4,
    column: 1,
    imageUrl: null,
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 4,
    column: 2,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 4,
    column: 3,
    imageUrl: null,
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 4,
    column: 4,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 4,
    column: 5,
    imageUrl: null,
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 4,
    column: 6,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 4,
    column: 7,
    imageUrl: null,
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 5,
    column: 1,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 5,
    column: 2,
    imageUrl: null,
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 5,
    column: 3,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 5,
    column: 4,
    imageUrl: scissorsURL,
    team: 'B',
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 5,
    column: 5,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 5,
    column: 6,
    imageUrl: null,
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 5,
    column: 7,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 6,
    column: 1,
    imageUrl: scissorsURL,
    team: 'B',
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 6,
    column: 2,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 6,
    column: 3,
    imageUrl: null,
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 6,
    column: 4,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 6,
    column: 5,
    imageUrl: null,
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 6,
    column: 6,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 6,
    column: 7,
    imageUrl: scissorsURL,
    team: 'B',
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 7,
    column: 1,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 7,
    column: 2,
    imageUrl: stoneURL,
    team: 'B',
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 7,
    column: 3,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 7,
    column: 4,
    imageUrl: paperURL,
    Kingdom: 'B',
    team: 'B',
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 7,
    column: 5,
    imageUrl: null,
    valid: false,
  },
  {
    isOption: false,
    press: false,
    row: 7,
    column: 6,
    imageUrl: stoneURL,
    team: 'B',
    valid: true,
  },
  {
    isOption: false,
    press: false,
    row: 7,
    column: 7,
    imageUrl: null,
    valid: false,
  },
];
export {data};
